apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: harbor.134.209.138.125.nip.io/team-admin/backstage:19
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backstage
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage
                  key: POSTGRES_PASSWORD
            - name: DNS
              valueFrom:
                secretKeyRef:
                  name: backstage
                  key: DNS
            - name: GITEA_SECRET
              valueFrom:
                secretKeyRef:
                  name: backstage
                  key: GITEA_SECRET
      