apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: basic-service
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'basic-service-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://gitea.134.209.138.125.nip.io/otomi/argo-workload.git
        targetRevision: HEAD
        path: 'basic-service-{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: 'basic-service-{{cluster}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true