apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-site-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-site-dev
  template:
    metadata:
      annotations:
        policy.otomi.io/ignore-sidecar: container-limits,psp-allowed-users
      labels:
        app: example-site-dev
    spec:
      containers:
        - name: example-site-dev
          image: harbor.134.209.138.125.nip.io/team-admin/example-site:2
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: 64Mi
              cpu: 100m
            requests:
              memory: 64Mi
              cpu: 100m
          securityContext:
            runAsUser: 1001
