apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-service-dev
  template:
    metadata:
      annotations:
        policy.otomi.io/ignore-sidecar: container-limits,psp-allowed-users
      labels:
        app: basic-service-dev
    spec:
      containers:
        - name: basic-service
          image: harbor.134.209.138.125.nip.io/team-admin/basic-service:4
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: '64Mi'
              cpu: '100m'
            requests:
              memory: '64Mi'
              cpu: '100m'
          securityContext:
            runAsUser: 1001
          env:
            - name: test
              valueFrom:
                secretKeyRef:
                  name: basic-service
                  key: test