apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service-prod
  template:
    metadata:
      annotations:
        policy.otomi.io/ignore-sidecar: container-limits,psp-allowed-users
      labels:
        app: example-service-prod
    spec:
      containers:
        - name: example-service-prod
          image: harbor.134.209.138.125.nip.io/team-admin/example-service:4
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: 64Mi
              cpu: 100m
            requests:
              memory: 64Mi
              cpu: 100m
          securityContext:
            runAsUser: 1001
